--------------------------------------------
-- CLINIC MANAGEMENT SYSTEM DATABASE
-- USER: C##CLINIC
--------------------------------------------

--------------------------------------------
-- 1. DEPARTMENT TABLE
--------------------------------------------

CREATE TABLE Department (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(100) NOT NULL UNIQUE,
    head_doctor_id NUMBER,
    CONSTRAINT pk_department PRIMARY KEY (department_id)
);

--------------------------------------------
-- 2. PATIENT TABLE
--------------------------------------------

CREATE TABLE Patient (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    gender VARCHAR2(10),
    date_of_birth DATE,
    phone VARCHAR2(15) UNIQUE,
    email VARCHAR2(100) UNIQUE,
    address VARCHAR2(200),
    registration_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_patient PRIMARY KEY (patient_id),
    CONSTRAINT chk_gender CHECK (gender IN ('Male','Female','Other'))
);

--------------------------------------------
-- 3. DOCTOR TABLE
--------------------------------------------

CREATE TABLE Doctor (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    specialization VARCHAR2(100),
    phone VARCHAR2(15),
    email VARCHAR2(100),
    department_id NUMBER NOT NULL,

    CONSTRAINT pk_doctor PRIMARY KEY (doctor_id),

    CONSTRAINT fk_doctor_department
        FOREIGN KEY (department_id)
        REFERENCES Department(department_id)
);

--------------------------------------------
-- 4. ADD DEPARTMENT HEAD FK
--------------------------------------------

ALTER TABLE Department
ADD CONSTRAINT fk_department_head
FOREIGN KEY (head_doctor_id)
REFERENCES Doctor(doctor_id);

--------------------------------------------
-- 5. STAFF TABLE
--------------------------------------------

CREATE TABLE Staff (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    role VARCHAR2(100),
    phone VARCHAR2(15),
    department_id NUMBER,

    CONSTRAINT pk_staff PRIMARY KEY (staff_id),

    CONSTRAINT fk_staff_department
        FOREIGN KEY (department_id)
        REFERENCES Department(department_id)
);

--------------------------------------------
-- 6. APPOINTMENT TABLE
--------------------------------------------

CREATE TABLE Appointment (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    appointment_date DATE NOT NULL,
    time_slot VARCHAR2(20) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Scheduled',

    CONSTRAINT pk_appointment PRIMARY KEY (appointment_id),

    CONSTRAINT fk_appointment_patient
        FOREIGN KEY (patient_id)
        REFERENCES Patient(patient_id),

    CONSTRAINT fk_appointment_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES Doctor(doctor_id),

    CONSTRAINT chk_status
        CHECK (status IN ('Scheduled','Completed','Cancelled'))
);

--------------------------------------------
-- PREVENT DOUBLE BOOKING
--------------------------------------------

ALTER TABLE Appointment
ADD CONSTRAINT unique_doctor_slot
UNIQUE (doctor_id, appointment_date, time_slot);

--------------------------------------------
-- 7. MEDICAL RECORD TABLE
--------------------------------------------

CREATE TABLE Medical_Record (
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id NUMBER UNIQUE,
    symptoms CLOB,
    diagnosis CLOB,
    treatment_notes CLOB,

    CONSTRAINT pk_medical_record PRIMARY KEY (record_id),

    CONSTRAINT fk_record_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES Appointment(appointment_id)
);

--------------------------------------------
-- 8. PRESCRIPTION TABLE
--------------------------------------------

CREATE TABLE Prescription (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id NUMBER UNIQUE,
    issue_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_prescription PRIMARY KEY (prescription_id),

    CONSTRAINT fk_prescription_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES Appointment(appointment_id)
);

--------------------------------------------
-- 9. MEDICATION TABLE
--------------------------------------------

CREATE TABLE Medication (
    medication_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    prescription_id NUMBER NOT NULL,
    medicine_name VARCHAR2(100) NOT NULL,
    dosage VARCHAR2(50),
    frequency VARCHAR2(50),
    duration VARCHAR2(50),

    CONSTRAINT pk_medication PRIMARY KEY (medication_id),

    CONSTRAINT fk_medication_prescription
        FOREIGN KEY (prescription_id)
        REFERENCES Prescription(prescription_id)
);

--------------------------------------------
-- 10. BILLING TABLE
--------------------------------------------

CREATE TABLE Billing (
    bill_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id NUMBER UNIQUE,
    amount NUMBER(10,2) NOT NULL,
    payment_mode VARCHAR2(20),
    payment_status VARCHAR2(20) DEFAULT 'Pending',
    payment_date DATE,

    CONSTRAINT pk_billing PRIMARY KEY (bill_id),

    CONSTRAINT fk_billing_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES Appointment(appointment_id),

    CONSTRAINT chk_payment_mode
        CHECK (payment_mode IN ('Cash','Card','UPI','Online')),

    CONSTRAINT chk_payment_status
        CHECK (payment_status IN ('Pending','Paid','Cancelled'))
);

--------------------------------------------
-- TRIGGER 1: PREVENT DOUBLE BOOKING
--------------------------------------------

CREATE OR REPLACE TRIGGER prevent_double_booking
BEFORE INSERT ON Appointment
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM Appointment
    WHERE doctor_id = :NEW.doctor_id
    AND appointment_date = :NEW.appointment_date
    AND time_slot = :NEW.time_slot;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Doctor already has an appointment in this slot.'
        );
    END IF;
END;
/

--------------------------------------------
-- TRIGGER 2: AUTO UPDATE PAYMENT STATUS
--------------------------------------------

CREATE OR REPLACE TRIGGER update_payment_status
BEFORE UPDATE ON Billing
FOR EACH ROW
BEGIN
    IF :NEW.payment_date IS NOT NULL THEN
        :NEW.payment_status := 'Paid';
    END IF;
END;
/

--------------------------------------------
-- TRIGGER 3: AUTO CREATE BILL AFTER APPOINTMENT
--------------------------------------------

CREATE OR REPLACE TRIGGER create_bill_after_appointment
AFTER INSERT ON Appointment
FOR EACH ROW
BEGIN
    INSERT INTO Billing (
        appointment_id,
        amount,
        payment_status
    )
    VALUES (
        :NEW.appointment_id,
        500,
        'Pending'
    );
END;
/

--------------------------------------------
-- SAMPLE DATA
--------------------------------------------

INSERT INTO Department (department_name) VALUES ('Cardiology');
INSERT INTO Department (department_name) VALUES ('Dermatology');
INSERT INTO Department (department_name) VALUES ('Neurology');

INSERT INTO Doctor (name, specialization, phone, email, department_id)
VALUES ('Dr. Amit Sharma','Cardiologist','9876543210','amit@clinic.com',1);

INSERT INTO Doctor (name, specialization, phone, email, department_id)
VALUES ('Dr. Priya Mehta','Dermatologist','9876543211','priya@clinic.com',2);

INSERT INTO Doctor (name, specialization, phone, email, department_id)
VALUES ('Dr. Raj Patel','Neurologist','9876543212','raj@clinic.com',3);

UPDATE Department SET head_doctor_id=1 WHERE department_id=1;
UPDATE Department SET head_doctor_id=2 WHERE department_id=2;
UPDATE Department SET head_doctor_id=3 WHERE department_id=3;

INSERT INTO Patient (name,gender,date_of_birth,phone,email,address)
VALUES ('Rahul Mehta','Male',DATE '1995-05-10','9123456789','rahul@gmail.com','Mumbai');

INSERT INTO Patient (name,gender,date_of_birth,phone,email,address)
VALUES ('Sneha Shah','Female',DATE '1998-08-22','9234567890','sneha@gmail.com','Pune');

--------------------------------------------
-- APPOINTMENTS
-- BILLING ROWS AUTO CREATED BY TRIGGER
--------------------------------------------

INSERT INTO Appointment (patient_id,doctor_id,appointment_date,time_slot)
VALUES (1,1,DATE '2026-04-01','10:00-10:30');

INSERT INTO Appointment (patient_id,doctor_id,appointment_date,time_slot)
VALUES (2,2,DATE '2026-04-01','11:00-11:30');

--------------------------------------------
-- MEDICAL RECORD
--------------------------------------------

INSERT INTO Medical_Record (appointment_id,symptoms,diagnosis,treatment_notes)
VALUES (1,'Chest pain','Hypertension','Medication prescribed');

--------------------------------------------
-- PRESCRIPTION
--------------------------------------------

INSERT INTO Prescription (appointment_id) VALUES (1);

INSERT INTO Medication (prescription_id,medicine_name,dosage,frequency,duration)
VALUES (1,'Aspirin','75mg','Once daily','7 days');

--------------------------------------------
-- UPDATE BILLING (PAYMENT)
-- BILL CREATED AUTOMATICALLY BY TRIGGER
--------------------------------------------

UPDATE Billing
SET payment_mode='UPI',
    payment_date=SYSDATE
WHERE appointment_id=1;

COMMIT;

--------------------------------------------
-- VERIFY DATA
--------------------------------------------

SELECT * FROM Patient;
SELECT * FROM Doctor;
SELECT * FROM Appointment;
SELECT * FROM Billing;